// list
export const ITEM_LIST_FETCH_SUCCESS = 'ITEM_LIST_FETCH_SUCCESS';
export const ITEM_ADD_SUCCESS = 'ITEM_ADD_SUCCESS';
export const ITEM_REMOVE_SUCCESS = 'ITEM_REMOVE_SUCCESS';
export const ITEM_PAGE_REMOVE_SUCCESS = 'ITEM_PAGE_REMOVE_SUCCESS';

// history
export const HISTORY_FETCH_SUCCESS = 'HISTORY_FETCH_SUCCESS';

// Page
export const PAGE_FETCH_SUCCESS = 'PAGE_FETCH_SUCCESS';

// form
export const FORM_RESET_SUCCESS = 'FORM_RESET_SUCCESS';
export const FORM_RESET_FAILED = 'FORM_RESET_FAILED';

export const FORM_RESTORE_SUCCESS = 'FORM_RESTORE_SUCCESS';
export const FORM_RESTORE_FAILED = 'FORM_RESTORE_FAILED';

export const FORM_AUTO_DETECT_SUCCESS = 'FORM_AUTO_DETECT_SUCCESS';
export const FORM_AUTO_DETECT_FAILED = 'FORM_AUTO_DETECT_FAILED';

// Error
export const ERROR = 'ERROR';

// session
export const SESSION_RESTORE_SUCCESS = 'SESSION_RESTORE_SUCCESS';
export const SESSION_LOGIN_SUCCESS = 'SESSION_LOGIN_SUCCESS';
export const SESSION_LOGOUT_SUCCESS = 'SESSION_LOGOUT_SUCCESS';
